open System
open System.Data
open System.Data.SqlClient

let bigGrossQuery = "SELECT c.accountid,
       c.shortname
FROM dbo.CLIENTACCOUNT AS c
WHERE c.shortname IN ( 'mackie', 'felger', 'killsu', 'coatsc', 'sklar', 'bergern', 'waugh', 'oreilly3', 'murphyw',
                       'swantr', 'grabias', 'adeold', 'lagrotte', 'stevensj', 'stevensh', 'sedan', 'haba', 'parlf2',
                       'spanier', 'baedwa', 'wishnow', 'hamiltp', 'bachew', 'hilloc', 'matthh', 'huntal', 'willa2',
                       'reindom', 'katrsr', 'hiljef', 'manmar', 'mollsa', 'edwards2', 'partor', 'princ2', 'berg',
                       'stewac', 'hyman', 'robsa3', 'bermar', 'walrog', 'robsa5', 'robsa1', 'strausr', 'sarbla',
                       'bachwe', 'mchenry', 'lindel', 'cliacw', 'hayeel', 'leebae', 'iorthe', 'zweig', 'wilsyl',
                       'ldjinv', 'singer', 'chapra', 'F76484', 'patalano', 'swopet', 'chapmado', 'lightpe', 'ellija',
                       'marsden', 'A90862', 'lawler', 'reesja', 'smihol', 'brockw', 'clarkal', 'horowitz', 'rosgbl',
                       'garabed', 'usatm', 'reedlt', 'footaj', 'mickga', 'blackl', 'jeweke', 'lirnar', 'mwjinv',
                       'smithh', 'granka', 'osgoch', 'water2', 'stamm', 'bazesa', 'sunlen', 'ioradr', 'markjs',
                       'montgo', 'rhoael', 'watsfa', 'campa1', 'dunime', 'semsco', 'estrju', 'monttr', 'norrma',
                       'reedmd', 'pitca187', 'boatts', 'marrvi', 'pitca188', 'lidfog', 'S80909', 'harige', 'boattl',
                       'robger', 'davego', 'yooric', 'karfol', 'barryfa', 'kellyj', 'yara', 'naalbe', 'patefa',
                       'albfai', 'iorith', 'weisbp', 'kidmar', 'johbla', 'deanvi', 'colbc2', 'basker', 'roseven',
                       'druber', 'hobglo', 'sonven', 'kreijo', 'dunnfa', 'kidrmi', 'bergno', 'gengbl', 'pateam',
                       'golarr', 'kidmi1', 'dunner', 'dainor', 'frasst', 'currma', 'deanna', 'hilric', 'kidbec',
                       'gottbr', 'kidmi2', 'mellin', 'lelshe', 'whepa1', 'kidkat', 'rivand', 'clappw', 'wernri',
                       'handsur', 'passaro', 'ethgbl', 'sherwood', 'krasju', 'iortjr', 'dunlfr', 'jonesp', 'invest34',
                       'krasma', 'davlei', 'donaka', 'ioriot', 'dunru3', 'mahshe', 'skidmo', 'slater', 'iralan',
                       'smytme', 'citiso', 'connbl', 'sedloc', 'karred', 'halsaa', 'sorfam', 'ethdav', 'carnel',
                       'serwhi', 'cinade', 'hestst', 'diagbl', 'clapp43', 'ricsay', 'robfra', 'marrav', 'peeklp',
                       'kenhoj', 'Y73013', 'jacobm', 'pitca287', 'abblei', 'hommic', 'clapmat', 'ertder', 'huntjo',
                       'huntle', 'lirana', 'homkri', 'undllc', 'whepa2', 'gillca', 'hood', 'lexisp', 'myemic',
                       'pitca285', 'mareli', 'saatru', 'kopdek', 'calltr', 'newted', 'mnclapp', 'hildro', 'wolmei',
                       'calero', 'pitca282', 'arylen', 'pitca283', 'henniw', 'neurev', 'rogech', 'wenoje', 'garand',
                       'S80952', 'pitca289', 'skachr', 'makera', 'bhabvi', 'kasimp', 'clappr', 'jamind', 'mckenk',
                       'multre', 'chinth', 'kenall', 'cantma', 'swakar', 'pitca277', 'mallcr', 'fourtha', 'mulfbe',
                       'suchra', 'brouka', 'nelint', 'pitca275', 'sharim', 'burddo', 'skokan', 'invest28', 'chalap',
                       'racbro', 'corptr', 'rachel', 'trbgbl', 'calfam', 'carnem', 'rochho', 'pitca291', 'slstru',
                       'cladra', 'twoabe', 'chilsc', 'fthom1', 'rodray', 'desimi', 'edeshe', 'pitca288', 'multrj',
                       'tonbur', 'angelo', 'wilams', 'multrc', 'hirfam', 'warfam', 'wenjer', 'blawil', 'dolinv',
                       'benana', 'inssto', 'ducund', 'mulfbc', 'harrje', 'hennwi', 'hagetr', 'wilmob', 'lamhol',
                       'davujr', 'kapkom', 'zagli2', 'frthoc', 'mezzkri', 'whibus', 'fambae', 'homega', 'denjag',
                       'ronnic', 'hoanph', 'fthoma', 'capsno', 'mileri', 'muraba', 'tobyl2', 'kuhfam', 'S25938',
                       'drevtr', 'equtru', 'kutjay', 'famru3', 'pitca293', 'robmac', 'cynlun', 'emeven', 'primaj',
                       'robbes', 'becgav', 'dilfdn', 'johise', 'galkar', 'pitca292', 'bfipar', 'pitca301', 'rasamu',
                       'truric', 'warerc', 'schaji', 'saliir', 'burluc', 'bullas', 'knoxse', 'lesltd', 'debrai',
                       'ruthar', 'werham', 'engl2a', 'A96279', 'hackel', 'kermar', 'pitca303', 'S83094', 'rimdec',
                       'A99593', 'S83088', 'maslow', 'tsomic', 'mnuhea', 'katwil', 'mcemal', 'cyngbl', 'booot10',
                       'kesdav', 'holetr', 'tynmar', 'joahun', 'spinen', 'irryou', 'copgeo', 'mcelma', 'wayeli',
                       'kniewi', 'megdor', 'emven2', 'hudsla', 'alerag', 'Y89471', 'colliw', 'rourut', 'wilpen',
                       'stdemo', 'haireb', 'jamscu', 'frport', 'ekeitr', 'loboti', 'kutger', 'chanac', 'huahow',
                       'saddca', 'wernru', 'hunkor', 'beulah2', 'wenric', 'jeboyd', 'calhoun', 'ricdav', 'jacoru',
                       'jenise', 'lindan4', 'issjac', 'korbel', 'lumpki', 'dierjo', 'ricise', 'crowed', 'esrami',
                       'quifam', 'shlamb', 'gpkinv', 'stegin', 'bakinv', 'edwmc2', 'ragkat', 'javlop', 'lundb1',
                       'ricma1', 'whetru', 'ebjdru', 'englst', 'bricar', 'kucken', 'maryou', 'butnce', 'angsto',
                       'avatru', 'browars', 'barasi', 'shahjh', 'vyasvi', 'phisma', 'tudefa', 'haeile', 'wymant',
                       'bresso', 'issnic', 'edwmc1', 'ventad', 'ikedas', 'ushdan', 'stoll', 'smarta', 'sibtru',
                       'garbno', 'gulfam', 'mjpsml', 'naqvis', 'sjandi', 'cavarc', 'gstmpf', 'hayidb', 'jayday',
                       'twetex', 'sundan', 'lgyoun', 'wheter', 'brorig', 'redusp', 'gianch', 'gisnes', 'kolkst',
                       'dpenni', 'kostru', 'lrishn', 'reskes', 'jolley', 'rooger', 'cullja', 'daryas', 'simmoa',
                       'neyrag', 'terwhe', 'powpow', 'kolbin', 'meride', 'bookec', 'avalo2', 'mk2011', 'edwric',
                       'groenj', 'mcgjef', 'holrag', 'buwood', 'gulrob', 'priphi', 'nosric', 'evavan', 'glenki',
                       'fishtr', 'wdpllc', 'raglan', 'thmorr', 'wangeu', 'robsus', 'joskei', 'jaclaw', 'owensj',
                       'lissta', 'robsa7', 'moredi', 'ropass', 'jagail', 'watver', 'nogach', 'darabi', 'philke',
                       'pitca276', 'jhutch', 'pettwt', 'tunsta', 'jollon', 'bradhi', 'walt4j', 'forwyn', 'jacste',
                       'simmop', 'edwsti', 'jamben', 'webric', 'timmac', 'simpsn', 'slover', 'ragjoh', 'ultrac',
                       'wbloom', 'temwil', 'bjfaru', 'mulirr', 'falnam', 'tarada', 'exacar', 'hicky4', 'davjoa',
                       'emwdyn', 'joscol', 'tanfam', 'hughar', 'doweal', 'walt1j', 'roches', 'ephrag', 'spenly',
                       'sekdyn', 'royfke', 'porfed', 'thoand', 'lynter', 'lansco', 'albhof', 'kymead', 'hofwar',
                       'ashintl', 'daviru', 'garrap', 'flilor', 'rageli', 'jessme', 'nandud', 'jgblac', 'lydiab',
                       'donrap', 'landel', 'sembri', 'semlin', 'denary', 'semmat', 'flinnn', 'anderswp', 'taviti',
                       'avitia', 'pjcrev', 'ragmar', 'belltru', 'jamkay', 'issues', 'wibaer', 'becktr', 'mheard',
                       'buckjo', 'classu', 'flidav', 'bertjd', 'sararu', 'andede', 'cahnfa', 'fboezb', 'batway',
                       'noveli', 'morrab', 'glesch', 'mcmain', 'jostin', 'tollys', 'chalin', 'waltj5', 'proved',
                       'sapale', 'rjweil', 'kelsur', 'tiflan', 'hyunru', 'smthtr', 'biflan', 'holews', 'nelyol',
                       'cornsu', 'meflan', 'delhed', 'liperl', 'haefru', 'schaeb', 'marles', 'boflan', 'tuocap',
                       'standf', 'schaur', 'lonnpr', 'bulljb', 'higgtr', 'kraksa', 'koplo2', 'twetle', 'shakin',
                       'litdan', 'glemgm', 'amarit', 'anntal', 'hackgt', 'consar', 'littna', 'seflan', 'savjan',
                       'ruffin', 'conand', 'crabfa', 'krankk', 'cittru', 'whitjj', 'yelvig', 'mosefu', 'lundmi3',
                       'lundbr', 'pitca307', 'richus', 'pitca308', 'lundsh', 'schstr', 'colcar', 'koplowr', 'jacpam',
                       'kritcr', 'odysse', 'hagejo', 'lunds1', 'hubgej', 'hagebr', 'gropmi', 'martta', 'bendes',
                       'umcorp', 'sixbar', 'coredi', 'ernric', 'newhka', 'silvea', 'wurtel', 'alihar', 'krien2',
                       'wileng', 'jacen2', 'kabrob', 'jasen2', 'herrmann', 'mulsys', 'whetsto2', 'blacjg', 'riosdo',
                       'flanti', 'millerv', 'syden2', 'waltjm', 'clarker', 'mjpintl', 'kotafr', 'hallle', 'skorma',
                       'kingda', 'spanri', 'hamipa', 'henrywi', 'hoey', 'ritasu', 'bristow', 'evanjt', 'coachr',
                       'TC0492', 'aronju', 'santarel', 'auerbach', 'robite', 'sdcorn', 'TC0619', 'lighte', 'peteja',
                       'evanal', 'craven', 'sandel', 'greedo', 'jachinow', 'helmel', 'gantga', 'conlmi', 'fpirce',
                       'bentan', 'oliann', 'TC0506', 'TC0433', 'kerrsc', 'faccak', 'TC0434', 'schmrr', 'pgjbut',
                       'gorbri', 'motion', 'harrly', 'murall', 'andewt', 'tecari', 'melngr', 'heftif', 'mccuda',
                       'thojan', 'hardbb', 'TC0509', 'TC0508', 'vers60', 'albedo', 'labiwi', 'garajo', 'mcelcl',
                       'vers70', 'tc0703', 'w40634', 'willec', 'chapmr', 'satusk', 'johned', 'robinv', 'brarob',
                       'clapfa', 'waltel', 'schrer', 'fmtdte', 'pndhee', 'W09901', 'pmdpra', 'T38721', 'flanbr',
                       'tc0751', 'astral', 'mccuad', 'chitho', 'chrral', 'sitena', 'smimic', 'thurwi', 'waldje',
                       'robjaf', 'V51798', 'bribet', 'clapjam', 'picksa', 'chrste', 'smiger', 'batber', 'huntch',
                       'T35420', 'xwiown', 'llbinh', 'lobtil', 'lobodo', 'clapad', 'hameri', 'delsco', 'johnstdb',
                       'whimil', 'briles', 'powrob', 'dschmg', 'fretho', 'zarmas', 'heibru', 'giroma', 'coylee',
                       'haleca', 'morgch', 'shenda', 'bushnell', 'DOYLDE', 'roseji', 'johntrjr', 'A96355', 'higact',
                       'TC0489', 'johnad', 'shanje', 'audsm2', 'clajaq', 'halpmi', 'johnki', 'exepti', 'sesekf',
                       'branby', 'bharbv', 'thober', 'dakoci', 'boldom', 'houphu', 'V13195', 'glazdi', 'hillri',
                       'davihe', 'kelljb', 'burlen', 'khopch2', 'mcctru', 'heibri', 'danhil', 'rusejd', 'walabe',
                       'rose86', 'jwminv', 'malloy', 'V35549', 'canter', 'lucbur', 'applba', 'janehe', 'bremel',
                       'amisna', 'trusmc', 'labfam', 'shepet', 'V35428', 'shanjt', 'dunfam', 'fisraf', 'zakijo',
                       'ferade', 'jabarr', 'harson', 'duboje', 'jshali', 'B92408', 'smymei', 'damage', 'W97469',
                       'gooedy', 'appeba', 'hilmag', 'kienju', 'eugmey', 'knetru', 'olispe', 'volume', 'drummb',
                       'krabju', 'V14654', 'dedred', 'hulliv', 'collvt', 'V35564', 'chagre', 'U33825', 'giangs',
                       'norrob', 'judeps', 'heljan', 'dsouth', 'huneli', 'smitln', 'U46517', 'v42610', 'sdlktj',
                       'houwil', 'frrich', 'sampda', 'taypas', 'againn', 'olinsp', 'corned', 'willhe', 'V51717',
                       'drumbe', 'lobhol', 'sldjke', 'heldav', 'B35868', 'colbyc', 'junumi', 'poucaq', 'timsuz',
                       'elisil', 'miltho', 'annpet', 'chekir', 'leisco', 'henria', 'V35170', 'symjan', 'exgst',
                       'daplen', 'myermi', 'higgac', 'rothss', 'bisoil', 'trussl', 'V42582', 'termas', 'ldcart',
                       'smitcs', 'lauero', 'jamsha', 'barblt', 'gsshan', 'annher', 'tietla', 'aveest', 'reirmr',
                       'monsin', 'johnfr', 'cankat', 'hanwoo', 'busfre', 'jshaug', 'BFFSDS', 'ernsar', 'fisspv',
                       'skarch', 'brahil', 'nesomd', 'johkau', 'T85176', 'frstfl', 'bumpus', 'trulyn', 'kinzso',
                       'fhburr', 'V37370', 'BRAGEF', 'cstspi', 'B40745', 'phispi', 'C13560', 'lddrei', 'mccamp',
                       'kathil', 'jefber', 'suswoo', 'joycol', 'ajsksk', 'dakots', 'walgre', 'hiltru', 'lewhal',
                       'kincha', 'howija', 'heinwj', 'Y91654', 'diejoh', 'ricsja', 'wsrich', 'fcmaso', 'delsan',
                       'fregre', 'jelled', 'fmwake', 'sinmar', 'V40151', 'lburri', 'hildom', 'margrw', 'taylbr',
                       'trefam', 'mungal', 'rgrema', 'mjcrom', 'klemca', 'gavgre', 'ortibe', 'nmeato', 'carbo1',
                       'lefric', 'sopgre', 'sinlin', 'eaglev', 'fjfjfh', 'pallan', 'bcitib', 'lassyl', 'lasstl',
                       'dufami', 'clemen', 'ruscar', 'pracom', 'cesull', 'henter', 'carsta', 'B32686', 'E57553',
                       'whybet', 'heiduf', 'dakota', 'grewal', 'greeci', 'clrich', 'E58759', 'howida', 'chrkle',
                       'pehoma', 'levres', 'jacgra', 'annril', 'nangre', 'thodal', 'gavigr', 'fdgree', 'nodewa',
                       'sargre', 'jamgur', 'trulee', 'nesabr', 'pafish', 'hengre', 'goryre', 'laroti', 'greban',
                       'miclev', 'monphi', 'fresta', 'maydan', 'thorcu', 'scandi', 'modavi', 'brigot', 'iglirr',
                       'leewin', 'longdi', 'ruschr', 'mulfbj', 'lucart', 'paurus', 'grihil', 'eatmea', 'cooedw',
                       'dakcit', 'godman', 'oliwil', 'W72568', 'pigjam', 'cochdo', 'asstho', 'cartyl', 'bramna',
                       'delcit', 'alrllp', 'trusls', 'rrlevi', 'howiwi', 'kransa', 'julkra', 'husste', 'evaeli',
                       'residu', 'henrgr', 'deanho', 'rocpon', 'clarer', 'bargai', 'daskal', 'A95463', 'susmor',
                       'ncadad', 'thengu', 'Y90043', 'manchi', 'D91877', 'gianfc', 'niesen', 'watsof', 'sascha',
                       'rewham', 'bripat', 'arnojm', 'wmarkb', 'jampig', 'hendca', 'laupra', 'panhan', 'karpet',
                       'mahals', 'bernsj', 'trelos', 'merwil', 'friell', 'shatdo', 'chorev', 'E89036', 'deltru',
                       'ricjac', 'ntespi', 'wacker', 'FROSAL', 'elesha', 'whilit', 'E60816', 'trucit', 'baetru',
                       'switho', 'chilgo', 'b21212', 'vldav', 'maltda', 'wyasha', 'alejoa', 'krafam', 'korgin',
                       'juldal', 'cordak', 'citcor', 'dakotr', 'myloyd', 'A37113', 'whitfo', 'wynncj', 'bernon',
                       'jaddas', 'patrow', 'invkam', 'forsya', 'lucigl', 'citdel', 'richr1', 'scandm', 'E93284',
                       'dcitic', 'ellden', 'stoxus', 'davall', 'mouwlj', 'nesger', 'sefano', 'sunliv', 'madawi',
                       'brampe', 'v42936', 'E16202', 'meylan', 'halric', 'librel', 'kuhnek', 'regreg', 'moomar',
                       'hibarb', 'scagoo', 'guljoa', 'sitrja', 'citnab', 'daksou', 'lynjon', 'berice', 'pigoth',
                       'skocah', 'edgart', 'kuhnef', 'lonfam', 'dakoso', 'johnstda', 'citbnk', 'johsan', 'kienel',
                       'donley', 'ngutru', 'jahnhe', 'simpwk', 'ungeli', 'colbc1', 'zagliv', 'beerba', 'phuhoa',
                       'whitty', 'simpsw', 'johntheo', 'gulphi', 'souton', 'ginnwt', 'famell', 'paslan', 'bevlow',
                       'trciti', 'harori', 'jorboy', 'simkat', 'CARMCC', 'muhmin', 'junsan', 'matlow', 'davcar',
                       'vlartz', 'chrand', 'forsyt', 'V67032', 'c89606', 'weilro', 'carljo', 'brurev', 'barema',
                       'kimshe', 'charwe', 'lanexe', 'hilint', 'learyt', 'A97667', 'wiljen', 'erilau', 'keball',
                       'soutru', 'y89428', 'Y81254', 'judlev', 'susgos', 'hwajam', 'trujhk', 'reynon', 'tobans',
                       'patelt', 'richsn', 'kravpa', 'vallea', 'klefre', 'lawtr3', 'greetu', 'rrusst3', 'veltho',
                       'luabur', 'marmeg', 'kenher', 'helnag', 'famlau', 'lorjud', 'yimali', 'berleo', 'pattsp',
                       'hibert', 'urikes', 'survtr', 'myfmtr', 'henwoo', 'keldwi', 'lannfa', 'jencks', 'igljaa',
                       'dasout', 'elicoo', 'fredke', 'amberm', 'winreb', 'ushdal', 'davep', 'mobljr', 'rubada',
                       'betwit', 'pdrake', 'deb2at', 'kebalt', 'floric', 'josc95', 'Y89426', 'schmca', 'sumjam',
                       'KIRBJINT', 'Y89500', 'ebjdea', 'citdak', 'jentru', 'corbin', 'krasfa', 'afeltr', 'joncin',
                       'klint2', 'cromos', 'salroc', 'kauman', 'winkar', 'vieto2', 'Y89527', 'simmor', 'klinst',
                       'owesjr', 'susrob', 'picsar', 'vieto3', 'cesner', 'dfeltr', 'flanme', 'jejojr', 'demphi',
                       'winkev', 'saaeaf', 'brorid', 'dorowe', 'renday', 'Y88042', 'simmob', 'mikhal', 'noratr',
                       'tonluc', 'ganguy', 'KIRBFINT', 'grayla', 'rusri1', 'doldan', 'katsti', 'libret', 'lifben',
                       'lazcar', 'licktr', 'medfam', 'F11074', 'S84003', 'schaae', 'trusib', 'KIRBDINT', 'kompas',
                       'nelprd', 'mccuma', 'thorn', 'micclo', 'tobyl1', 'tonrub', 'iamhow', 'cititr', 'mpfgst',
                       'smamar', 'Y89031', 'teedpa', 'stedev', 'bramju', 'kaymit', 'karsim', 'carily', 'sisher',
                       'sefana', 'resgar', 'fredst', 'tcitic', 'derphi', 'telewu', 'carsch', 'Y89427', 'masost',
                       'giatru', 'whibey', 'micraw', 'whibew', 'Y89727', 'ginmaz', 'dasoci', 'fishfm', 'y89451',
                       'salvje', 'scandc', 'ricrya', 'angell', 'robace', 'S81687', 'valkat', 'naqsye', 'lausyk',
                       'berenf', 'AI1YP3', 'rogoju', 'peteed', 'Y91294', 'LITTLL', 'segoli', 'lactod', 'robcar',
                       'palmad', 'greewi', 'batdon', 'jolchr', 'rowpam', 'lauric', 'paucid', 'secam1', 'grifam',
                       'sharah', 'mceter', 'Y85129', 'trdfel', 'sherca', 'invard', 'famhic', 'johfen', 'saraea',
                       'johnac', 'ownsjr', 'cherev', 'julorn', 'maulou', 'mareda', 'hasbar', 'grimau', 'secra1',
                       'burjan', 'cebspt', 'bientr', 'marywa', 'dsrvio', 'citeaf', 'alleti', 'trustc', 'aritru',
                       'aliwhi', 'ONEMLL', 'tomnor', 'adpins', 'amipat', 'petpai', 'weinsi', 'stinjo', 'lousar',
                       'cititd', 'shepak', 'deciti', 'hommad', 'debloy', 'citide', 'blofam', 'khandi', 'tobrev',
                       'webelo', 'lanliv', 'secmi1', 'cortru', 'winmar', 'marweb', 'welcla', 'lpopln', 'gianfo',
                       'kleige', 'spolee', 'judlor', 'elmval', 'milere', 'sanshep', 'lipcrut', 'domlen', 'frekev',
                       'diasus', 'radtom', 'wincor', 'igljoh', 'combat', 'F11073', 'whihar', 'virmar', 'katman',
                       'jgill', 'fuelca', 'fredtr', 'martly', 'schnet', 'midela', 'wilgol', 'secth1', 'betwhy',
                       'gloros', 'trafel', 'incsvc', 'grewil', 'janmic', 'nelfam', 'delqua', 'whirut', 'ninbla',
                       'golchr', 'beckbr', 'mceans', 'mcelau', 'aledas', 'liebma', 'leakae', 'micack', 'daleaf',
                       'secgg2', 'simptr', 'secam2', 'lipcrat', 'evalar', 'rcrtru', 'lazby1', 'nehama', 'cartom',
                       'gosbar', 'robsa4', 'jamcoo', 'bergol', 'G26121', 'scjame', 'coujon', 'srhtch', 'robgot',
                       'weisch', 'stepel', 'hoffhv', 'hoffma', 'secth2', 'robsa8', 'dolchi', 'brotey', 'fjwalt',
                       'krrobe', 'guypau', 'percit', 'beapaw', 'robekr', 'deutsc', 'secra2', 'orizab', 'caruth',
                       'chils2', 'forwoo', 'kuredw', 'kannaj', 'stufam', 'simtrb', 'granca', 'stames', 'khandii',
                       'y89466', 'secgg1', 'natpau', 'shepan', 'hitkst', 'matest', 'secmi2', 'palkat', 'carlon',
                       'daames', 'leholi', 'glenma', 'dougas', 'jamher', 'robsa2', 'barnso', 'sbconn', 'sheltr',
                       'palmww', 'nosjun', 'lipsma', 'hartem', 'jillke', 'biccha', 'chidol', 'rubwad', 'fairin',
                       'powoff', 'pmklpe', 'msrhod', 'robsa6', 'bjfaea', 'atwoed', 'invpar', 'setgri', 'haefea',
                       'gagray', 'amesda', 'polzzi', 'bernjr', 'citper', 'kauchl', 'hopthe', 'trudel', 'poaels',
                       'amesst', 'beneco', 'oizcna', 'citits', 'natgel', 'boletr', 'harr97', 'kersts', 'jawejr',
                       'insglo', 'clabur', 'jonwil', 'invear', 'jemiwe', 'darobe', 'murale', 'riccar', 'karphe',
                       'harsti', 'steame', 'levrit', 'eujubi', 'pondon', 'sodako', 'ameste', 'meanwe', 'slseig',
                       'citart', 'hdrhod', 'dalyed', 'bootot', 'norcme', 'roseha', 'fernds', 'coojos', 'caswsh',
                       'nowmic', 'hamric', 'revbec', 'beekman', 'bluece', 'patnes', 'gorgra', 'ciarit', 'iklick',
                       'powjsp', 'marron', 'weinel', 'fitzms', 'chrmin', 'hundav', 'hicky5', 'hoffka', 'carhin',
                       'ltiinv', 'hatser', 'kameme', 'nicter', 'megood', 'kihill', 'segvon', 'oaktru', 'barkjo',
                       'barona', 'sumsco', 'dortru', 'gustaf', 'lesmar', 'norgol', 'carexa', 'maitru', 'G50879',
                       'denigo', 'marald', 'harryb', 'keensa', 'clault', 'maxame', 'sydeng', 'catwil', 'cottin',
                       'ropagr', 'mknott', 'dahill', 'jaceng', 'harole', 'gbergs', 'citwar', 'jillco', 'cidela',
                       'mehill', 'mgordo', 'grhill', 'redtru', 'hihill', 'milchi', 'crofam', 'plfalp', 'sarlou',
                       'harrtr', 'byrfam', 'waltfj', 'grenny', 'winkat', 'flanro', 'koefed', 'citisd', 'bennah',
                       'sutcli', 'jufain', 'ebscha', 'jopowe', 'shackt', 'pattel', 'beccak', 'spames', 'alhill',
                       'benari', 'buttra', 'dammann', 'tshack', 'dieliv', 'cmaria', 'olileh', 'gwoodt', 'wilcod',
                       'rogura', 'ronalm', 'berndb', 'sonard', 'uthers', 'katson', 'rebtin', 'insneo', 'rickmi',
                       'jayfis', 'gperki', 'lazby2', 'thehop', 'mvadon', 'trst12', 'davsus', 'roncha', 'kewlee',
                       'essman', 'kannat', 'gorbro', 'S87603', 'mardyn', 'kohdav', 'citsou', 'thelho', 'kaulau',
                       'thobru', 'jamika', 'zoeeng', 'gblfam', 'shepky', 'kotoha', 'fmfern', 'ebingr', 'litjoy',
                       'lawpag', 'shaham', 'amojoh', 'robaik', 'perart', 'liopng', 'siebmi', 'double', 'harr02',
                       'malewh', 'famqui', 'bettma', 'walsco', 'dubois', 'bakeaf', 'brukar', 'kbrlfa', 'jodenn',
                       'caruta', 'johwhi', 'thucar', 'jimdor', 'kapbon', 'merch3', 'conrub', 'elcfun', 'alddon',
                       'eargeo', 'marvtr', 'famnor', 'sgyllc', 'daskaj', 'chwalg', 'skinner', 'paones', 'skingr',
                       'ardson', 'jorgep', 'gocmut', 'fortef', 'merch1', 'G57687', 'davlom', 'stamaw', 'postin',
                       'gartim', 'beeeli', 'asarpo', 'rictal', 'krieng', 'richka', 'wrighe', 'kirtho', 'kuhnfa',
                       'wrightw', 'sauber', 'laumac', 'burnpa', 'annrfo', 'maxfle', 'davgro', 'daskam', 'shepft',
                       'jansch', 'artper', 'seibm2', 'bultad', 'briich', 'juliec', 'murch1', 'mercht', 'murch2',
                       'tincot', 'siehel', 'edmund', 'warhof', 'alletr', 'andrsh', 'collal', 'grfatr', 'lisagr',
                       'helltr', 'jaypar', 'leonng', 'leblon', 'jaseng', 'simste', 'mcemce', 'trustb', 'anncoo',
                       'nortru', 'lestng', 'clesta', 'chinpa', 'harish', 'poljos', 'polmax', 'polmay', 'barbcu',
                       'bosrob', 'chinwi', 'merch2', 'levytr', 'mariac', 'winerw', 'famros', 'mavjon', 'jonecy',
                       'reismi', 'plerus', 'gianct', 'opejam', 'prejoa', 'grondo', 'brndes', 'elstch', 'kewson',
                       'polsch', 'theran', 'chreva', 'lacour', 'saxfam', 'kailin', 'maclau', 'tavtan', 'cebtru',
                       'avifam', 'invlti', 'dunbar', 'harstu', 'rudleo', 'sumjad', 'jessdu', 'hariii', 'scandk',
                       'lisfat', 'bonson', 'maliro', 'krefam', 'brubec', 'rginve', 'jamant', 'meyerb', 'mshtru',
                       'Y88059', 'dollic', 'pyzide', 'evajol', 'reinintl', 'gdeinv', 'Y86093', 'wilmil', 'decrim',
                       'davhsm', 'carliz', 'bakesp', 'baulex', 'reglet', 'vanter', 'twquit', 'somfbo', 'wynncy',
                       'skocat', 'milbil', 'milamc', 'jamiec', 'grcnsr', 'grankr', 'slotda', 'trucor', 'lumiam',
                       'elield', 'grieoh', 'jberns', 'avaem2', 'taylyn', 'ava2intl', 'Y91502', 'carbur', 'meketr',
                       'citcit', 'dablat', 'jomasm', 'mkgood', 'BGFUEI', 'aldcat', 'fratch', 'Cudell', 'amsshe',
                       'higgdp', 'lesfre', 'mmgood', 'nicewo', 'rudolf', 'abatru', 'melmil', 'rncontr', 'jollch',
                       'thfrey', 'oriint', 'anstob', 'dalsp5', 'charkn', 'hogshi', 'serhat', 'jaffl', 'sosnem',
                       'vieto1', 'microv', 'kritck', 'maswol', 'Y87933', 'tunney', 'merbam', 'esvivo', 'majoma',
                       'F52408', 'lanpas', 'kuhnee', 'samdar', 'kritch', 'dclark', 'batdan', 'newann', 'winnli',
                       'masala', 'asofsm', 'dietri', 'wilkpa', 'isatau', 'splatt', 'callgr', 'mjmona', 'mairev',
                       'dilkhe', 'somevi', 'rusejo', 'Y84732', 'bowlin', 'stesha', 'kuhnej', 'addelt', 'thotow',
                       'bonsim', 'asofma', 'laksny', 'hirsba', 'wolfes', 'mryhig', 'manirm', 'citcou', 'ebctru',
                       'horowilt', 'elizhg', 'cornsd', 'sapsuz', 'olinst'
                     );"
let connectionString = "Server=uniondb.dev.paraport.com;Database=SCRUB_CAM;Trusted_Connection=True;"

let queryForAccounts() =
    use conn = new SqlConnection(connectionString)
    use command = new SqlCommand(bigGrossQuery, conn)
    command.CommandType <- CommandType.Text
    conn.Open()
    let reader = command.ExecuteReader(CommandBehavior.CloseConnection)
    [ while reader.Read() do yield (reader.GetInt32(0), reader.GetString(1)) ]
    
let executeSproc (accountId : int) = 
    use conn = new SqlConnection(connectionString)
    use dataAdapter = new SqlDataAdapter()
    use command = new SqlCommand("sp_TS_GetAccountSimBench", conn)
    let param = SqlParameter("@account_id", SqlDbType.Int)
    let dataSet = new DataSet()

    command.CommandType <- CommandType.StoredProcedure
    param.Value <- accountId
    command.Parameters.Add(param) |> ignore
    dataAdapter.SelectCommand <- command
    conn.Open()
    dataAdapter.Fill(dataSet) |> ignore

    let table = dataSet.Tables.[1]
    let filtered = table.Select("year_month = '201706' OR year_month = '201706 (first)'")
    filtered |> Array.sumBy (fun a -> System.Decimal.Parse(a.["end_market_value"].ToString()))

let main() =
    let accounts = queryForAccounts()
    let lines = accounts
                    |> List.map (fun (id, name) -> 
                                        let result = executeSproc id
                                        sprintf "%s,%f2" name result
                                    )
                    |> List.toArray
         
    System.IO.File.WriteAllLines(@"\\paraport\home share\Personal\ChristoB\out.csv", lines)